import { FlatCompat } from '@eslint/eslintrc';
import { dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

/**
 * The `lint` script shipped with the starter but ESLint did not, so
 * `npm run lint` failed on a fresh clone. Next's own config covers the rules
 * that matter here (hooks, imports, a11y basics).
 *
 * `next lint` is deprecated and removed in Next 16, so the script calls the
 * ESLint CLI directly — the migration path Next itself recommends.
 */
const config = [
  // next-env.d.ts is generated by Next on every build and must not be edited;
  // its triple-slash reference is Next's own, not ours.
  { ignores: ['.next/**', 'node_modules/**', 'out/**', 'next-env.d.ts'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default config;
